### ISSUE TITLE
genomenotebook for the human genome

### ISSUE THREAD

**Issue by wmorgans** [dbikard/genomenotebook#2]
Hi nice tool. 

I've been trying to get genome notebook to work with the human genome. I'm currently struggling to get the genes to display properly. For hg38 the UCSC golden path doesn't supply gff files, but gtf files (https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/). 

I've converted to gff via cufflinks. The browser tracks display the genes in the right locations but the gene names aren't annotated and hovering over the gene doesn't display the information about it. Just wondering if you've got any ideas for a fix for this?

Thanks,
Will

**Comment by dbikard** [comment]
Hi,
thank you for submitting an issue. At the moment genomenotebook only consider lines of the gff file with types "CDS", "repeat_region", "ncRNA", "rRNA" or "tRNA", and parses the attributes column of the gff file (should be column number 9) looking for attributes with the following format: "attribute_name=attribute_value;" At the moment we only extract attributes with the names: "locus_tag", "gene" and "product". If these attributes are not found in your column number 9 then nothing will be displayed. We could considering parsing more attribute names in the future. What are the attribute names you would be interested to see?

Best,
David

**Comment by wmorgans** [comment]
Hi,

Thanks for the quick reply. In my gff, column 9 of the transcript entries have the following attributes "ID=X;geneID=X;gene_name=X" where the geneID and gene_name fields are the same. I've modified the "geneID" field to "gene" (i.e. "ID=X;gene=X;gene_name=X") but the tracks still don't display gene names.

Best,
Will

**Comment by dbikard** [comment]
I've just released a new version of genomenotebook. You now have a lot of options to easily chose the feature types and attributes you want to show.  Check: https://dbikard.github.io/genomenotebook/options.html
You also don't need to provide a sequence file anymore if you are just interested in seeing the annotations. I tested it with human genome gff file from NCBI and it seems to work.

**Comment by dbikard** [comment]
Solved in new versions
