### ISSUE TITLE
docs update

### ISSUE THREAD

**Issue by seanrjohnson** [dbikard/genomenotebook#9]
In the "exporting plots" docs, there is a line that says:
"Plots can only be saved to svg if you initialise your GenomeBrowser using output_backend="svg". When mutliple tracks are displayed, an individual svg file will be saved for each track, as well as a combined svg file."

I believe I patched it to autodetect, so this isn't true anymore.

**Comment by seanrjohnson** [comment]
Also "Saving plots requires selenium and geckodriver." should be updated to "Saving plots to `.svg` or `.png` requires selenium and geckodriver. html export is supported without those dependencies."

**Comment by dbikard** [comment]
Thanks! Just fixed it.
